### ISSUE TITLE
Set selection doesn't work for the first time when data gets loaded

### ISSUE THREAD

**Issue by abhirb1** [etsy/AndroidStaggeredGrid#135]
When i use set selection for the first time when data gets loaded in grid it doesn't work but when i scroll the list then it works..I don't know how? Can anyone help me here?

**Comment by sandeep-m** [comment]
@abhirb1 Hi Abhi...I tried in th way you mention.But It is Crashing the app

**Comment by ChrisMpitzios** [comment]
it does scroll the gridview but if you try to scroll down immediatelly after the setselection execution it doesnot scroll. You have to scroll a little up and then you can scroll down.
