### ISSUE TITLE
Column out of position.

### ISSUE THREAD

**Issue by DoubleTime** [etsy/AndroidStaggeredGrid#168]
![device-2015-01-30-172500](https://cloud.githubusercontent.com/assets/5257978/5994868/cce3a762-aabe-11e4-8c48-f437fa66d5db.png)

I got this output with following step:

All my activity are fix portrait mode <pre>setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);</pre>

My first activity is Splash Screen and I placed my phone to landscape position after the loading is finish will go into Main Activity and the AndroidStaggeredGrid layout become like above picture. This layout is fine if my phone is in portrait position on Splash Screen.

Is there any way to overcome this??

**Comment by andreimarinescu** [comment]
I'm having a similar issue, did you ever track down what was going wrong?

**Comment by DoubleTime** [comment]
I removed <pre>android:configChanges="orientation|screenSize"</pre> in my AndroidManifest.xml
