### ISSUE TITLE
IndexOutOfBounds-Exception

### ISSUE THREAD

**Issue by tsemann** [etsy/AndroidStaggeredGrid#40]
Hi,

I encountered an error while scrolling through the Listview with Genymotion "Galaxy S4" with Android 4.3.

The error is:
<code>
E/MessageQueue-JNI(5118): Exception in MessageQueue callback: handleReceiveCallback
E/MessageQueue-JNI(5118): java.lang.IndexOutOfBoundsException: Invalid index 105, size is 1
E/MessageQueue-JNI(5118):   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/MessageQueue-JNI(5118):   at java.util.ArrayList.get(ArrayList.java:308)
E/MessageQueue-JNI(5118):   at com.etsy.android.grid.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:169)
E/MessageQueue-JNI(5118):   at com.etsy.android.grid.ExtendableListView.onTouchDown(ExtendableListView.java:818)
E/MessageQueue-JNI(5118):   at com.etsy.android.grid.ExtendableListView.onTouchEvent(ExtendableListView.java:686)
E/MessageQueue-JNI(5118):   at android.view.View.dispatchTouchEvent(View.java:7384)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1940)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
E/MessageQueue-JNI(5118):   at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
E/MessageQueue-JNI(5118):   at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1966)
E/MessageQueue-JNI(5118):   at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1418)
E/MessageQueue-JNI(5118):   at android.app.Activity.dispatchTouchEvent(Activity.java:2424)
E/MessageQueue-JNI(5118):   at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1914)
E/MessageQueue-JNI(5118):   at android.view.View.dispatchPointerEvent(View.java:7564)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3883)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3778)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5419)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5399)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5370)
E/MessageQueue-JNI(5118):   at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5493)
E/MessageQueue-JNI(5118):   at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
E/MessageQueue-JNI(5118):   at android.os.MessageQueue.nativePollOnce(Native Method)
E/MessageQueue-JNI(5118):   at android.os.MessageQueue.next(MessageQueue.java:132)
E/MessageQueue-JNI(5118):   at android.os.Looper.loop(Looper.java:124)
E/MessageQueue-JNI(5118):   at android.app.ActivityThread.main(ActivityThread.java:5103)
E/MessageQueue-JNI(5118):   at java.lang.reflect.Method.invokeNative(Native Method)
E/MessageQueue-JNI(5118):   at java.lang.reflect.Method.invoke(Method.java:525)
E/MessageQueue-JNI(5118):   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/MessageQueue-JNI(5118):   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/MessageQueue-JNI(5118):   at dalvik.system.NativeStart.main(Native Method)
E/AndroidRuntime(5118): FATAL EXCEPTION: main
E/AndroidRuntime(5118): java.lang.IndexOutOfBoundsException: Invalid index 105, size is 1
E/AndroidRuntime(5118):     at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
E/AndroidRuntime(5118):     at java.util.ArrayList.get(ArrayList.java:308)
E/AndroidRuntime(5118):     at com.etsy.android.grid.HeaderViewListAdapter.isEnabled(HeaderViewListAdapter.java:169)
E/AndroidRuntime(5118):     at com.etsy.android.grid.ExtendableListView.onTouchDown(ExtendableListView.java:818)
E/AndroidRuntime(5118):     at com.etsy.android.grid.ExtendableListView.onTouchEvent(ExtendableListView.java:686)
E/AndroidRuntime(5118):     at android.view.View.dispatchTouchEvent(View.java:7384)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2205)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1940)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2211)
E/AndroidRuntime(5118):     at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1912)
E/AndroidRuntime(5118):     at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:1966)
E/AndroidRuntime(5118):     at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1418)
E/AndroidRuntime(5118):     at android.app.Activity.dispatchTouchEvent(Activity.java:2424)
E/AndroidRuntime(5118):     at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:1914)
E/AndroidRuntime(5118):     at android.view.View.dispatchPointerEvent(View.java:7564)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:3883)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:3778)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3483)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3540)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3429)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3398)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3406)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3379)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5419)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5399)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5370)
E/AndroidRuntime(5118):     at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5493)
E/AndroidRuntime(5118):     at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:182)
E/AndroidRuntime(5118):     at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(5118):     at android.os.MessageQueue.next(MessageQueue.java:132)
E/AndroidRuntime(5118):     at android.os.Looper.loop(Looper.java:124)
E/AndroidRuntime(5118):     at android.app.ActivityThread.main(ActivityThread.java:5103)
E/AndroidRuntime(5118):     at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime(5118):     at java.lang.reflect.Method.invoke(Method.java:525)
E/AndroidRuntime(5118):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
E/AndroidRuntime(5118):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/AndroidRuntime(5118):     at dalvik.system.NativeStart.main(Native Method)
</code>

Maybe you can reproduce the error and solve the problem?

**Comment by andikapratama** [comment]
It's not just in Genymotion, I've encountered the same issue in Samsung Galaxy Tab and Nexus 7

**Comment by TonyTangAndroid** [comment]
For the record, I have also encountered this issue. Here is the crash log that might be of assistance in debug it. 

java.lang.IndexOutOfBoundsException: Invalid index 441, size is 1
            at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
            at java.util.ArrayList.get(ArrayList.java:308)
            at com.etsy.android.grid.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:230)
            at com.etsy.android.grid.ExtendableListView.obtainView(ExtendableListView.java:1584)
            at com.etsy.android.grid.ExtendableListView.makeAndAddView(ExtendableListView.java:1408)
            at com.etsy.android.grid.ExtendableListView.fillUp(ExtendableListView.java:1317)
            at com.etsy.android.grid.ExtendableListView.fillGap(ExtendableListView.java:1268)
            at com.etsy.android.grid.ExtendableListView.moveTheChildren(ExtendableListView.java:1235)
            at com.etsy.android.grid.ExtendableListView.access$600(ExtendableListView.java:59)
            at com.etsy.android.grid.ExtendableListView$FlingRunnable.run(ExtendableListView.java:1958)
            at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
            at android.view.Choreographer.doCallbacks(Choreographer.java:580)
            at android.view.Choreographer.doFrame(Choreographer.java:549)
            at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5256)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by 3rdstonejubin** [comment]
I also met this exception in Galaxy S3 (d2lterefreshspr) with Android 4.4. The following is the crash log from GA:

java.lang.IndexOutOfBoundsException: Invalid index 36, size is 1
at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
at java.util.ArrayList.get(ArrayList.java:308)
at com.etsy.android.grid.HeaderViewListAdapter.getView(HeaderViewListAdapter.java:230)
at com.etsy.android.grid.ExtendableListView.obtainView(ExtendableListView.java:1573)
at com.etsy.android.grid.ExtendableListView.makeAndAddView(ExtendableListView.java:1408)
at com.etsy.android.grid.ExtendableListView.fillUp(ExtendableListView.java:1317)
at com.etsy.android.grid.ExtendableListView.fillGap(ExtendableListView.java:1268)
at com.etsy.android.grid.ExtendableListView.moveTheChildren(ExtendableListView.java:1235)
at com.etsy.android.grid.ExtendableListView.access$600(ExtendableListView.java:59)
at com.etsy.android.grid.ExtendableListView$FlingRunnable.run(ExtendableListView.java:1958)
at android.view.Choreographer$CallbackRecord.run(Choreographer.java:814)
at android.view.Choreographer.doCallbacks(Choreographer.java:614)
at android.view.Choreographer.doFrame(Choreographer.java:583)
at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:800)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:146)
at android.app.ActivityThread.main(ActivityThread.java:5487)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
at dalvik.system.NativeStart.main(Native Method)

**Comment by heqingbao** [comment]
Eventually how to solve?
